name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Latest androguard aur pyinstaller install honge
        pip install androguard pyinstaller

    - name: Build with PyInstaller
      run: |
        cd android-threat-intel
        # --collect-all androguard ab bhi zaroori hai naye version ke liye
        pyinstaller --noconsole --onefile --collect-all androguard --name "APK_Forensic_Lab" gui_tool.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-App-Build
        path: android-threat-intel/dist/APK_Forensic_Lab.exe
